import { Toaster } from "@/components/ui/toaster";
import Providers from "@/lib/providers";
import { PropsWithChildren } from "react";
import "three-dots/dist/three-dots.css";
import { createClient } from "@/lib/supabase/server";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import Navbar from "./_components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <Notifications position="top-right" zIndex={1000} />
          <Providers>
            <div>
              <Navbar />
              <main>{children}</main>
              <Toaster />
            </div>
          </Providers>
        </MantineProvider>
      </body>
    </html>
  );
}
