import LogoutButton from "@/components/LogoutButton";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/lib/providers";
import Link from "next/link";
import { PropsWithChildren } from "react";
import "three-dots/dist/three-dots.css";
import { createClient } from "@/lib/supabase/server";
import "@mantine/core/styles.css";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en" className="h-full">
      <head>
        <ColorSchemeScript />
      </head>
      <body className="h-full">
        <MantineProvider>
          <Providers>
            <div>
              <main>{children}</main>
              <Toaster />
            </div>
          </Providers>
        </MantineProvider>
      </body>
    </html>
  );
}
